from . import asset_period
from . import asset_period_line
from . import res_master_mixin
from . import res_area
from . import res_building
from . import res_floor
from . import product_template
from . import cip_configuration
from . import asset_condition
from . import asset_segment
from . import asset_location
from . import account_asset
from . import account_move_line
from . import asset_cost_progress
from . import asset_progress
from . import asset_progress_line
from . import asset_assignment
from . import account_move
from . import account_asset_depreciation_line
from . import account_asset_account_move
from . import asset_source_line
