# -*- coding: utf-8 -*-
{
    'name': "MNC Accounting Reports",
    'summary': """
        Feature MNC accounting reports
    """,
    'description': """
        Feature MNC accounting reports
    """,
    'author': 'Hutomo Pebri Anditya',
    'category': 'Uncategorized',
    'version': '0.1',
    'depends': [
        'account',
        'report_xlsx',
        'mnc_menu_report',
        'ins_base_mnc',
    ],
    'data': [
        'security/ir.model.access.csv',
        'wizard/and_report_wizard.xml',
        'wizard/unapplied_receipt_register_report_wizard.xml',
        'wizard/invoice_prepayment_paid_supplier_wizard.xml',
        'wizard/aging_pdc_detail_report_wizard.xml',
        'wizard/aging_report_summary_wizard.xml',
        'wizard/aging_report_detail_wizard.xml',
        'wizard/collection_summary_report_wizard.xml',
        'wizard/sales_incentive_report_wizard.xml',
        'wizard/subledger_details_report_wizard.xml',
        'wizard/purchase_order_list_report_wizard.xml',
        # 'wizard/purchase_requisition_list_wizard.xml',
        'wizard/budget_vs_realization_report_wizard.xml',
        'wizard/statement_account_agency_report_wizard.xml',
        'wizard/statement_account_description_report_wizard.xml',
        'views/ar_receipt_report_menu.xml',
        'views/ar_unapplied_receipt_report_menu.xml',
        'views/unapplied_receipt_register_report_menu.xml',
        'views/aging_pdc_detail_menu.xml',
        'views/invoice_prepayment_paid_supplier_menu.xml',
        'views/aging_report_summary_menu.xml',
        'views/aging_report_detail_menu.xml',
        'views/collection_summary_report_menu.xml',
        'views/sales_incentive_report_menu.xml',
        'views/subledger_details_menu.xml',
        'views/purchase_order_list_report_menu.xml',
        # 'views/purchase_requisition_list_menu.xml',
        'views/budget_project_status_menu.xml',
        'views/budget_vs_realization_report_menu.xml',
        'views/pmis_project_task_line_views.xml',
        'views/statement_account_agency_menu.xml',
        'views/statement_account_description_menu.xml',
        'report/receipt_voucher_report_pdf.xml',
        'report/mnc_pdf_test_views.xml',
        'report/mnc_pdf_test2_views.xml',
        'report/aging_pdc_detail_report_pdf.xml',
        'report/and_report_paperformating.xml',
        'report/and_action_report.xml',
    ],
}
