# -*- coding: utf-8 -*-
{
    'name': "Base MNC",

    'summary': """
        Base module for MNC ERP
    """,

    'description': """
        Base module for MNC ERP
    """,

    'author': "Invosa Systems",
    'website': "https://www.invosa.com",

    'category': 'Hidden',
    'version': '0.1',

    'depends': [
        'base',
        'account',
        'account_accountant',
        'account_check_printing',
        'account_batch_payment',
        'account_document_reversal',
        'budget_control',
        'currency_manual_exchange_rate',
        'operating_unit',
        'project',
        'purchase',
        'purchase_request',
        'report_qweb_element_page_visibility',
        'stock',
        'stock_account',
        'fiscal_year_sync_app',
        'ins_asset',
        'ins_fixed_asset',
        'ins_accounting',
        'ins_purchase_approval',
        'ins_purchase_request_approval',
        'ins_tax_invoice',
        'ins_data_tax_invoice',
        'ins_miscellaneous',
        'ins_bi_exchange',
        'oi_bank_reconciliation',
        'report_xlsx',
        'one2many_mass_select_delete',

        # 'ins_project',
    ],

    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/mnc_security.xml',
        'security/buyer_security.xml',
        'security/res_assignee_invoice.xml',
        'security/partner_remit_security.xml',
        'security/ir_rule.xml',
        'data/purchase_data.xml',
        'data/mail_template.xml',
        'data/approval_mail_templates.xml',
        'data/account_chart_template.xml',
        'data/account.account.template.csv',
        'data/account_chart_template_post.xml',
        'data/account_tax_template.xml',
        'data/account_chart_template_configuration.xml',
        'data/ir_sequence_data.xml',
        'views/menu_views.xml',
        'views/purchase_views.xml',
        'views/master_episode.xml',
        'views/account_journal_views.xml',
        'views/account_move_views.xml',
        'views/account_move_line_views.xml',
        'views/account_batch_payment_views.xml',
        'views/account_payment_views.xml',  #
        'views/res_partner_views.xml',  #
        'views/res_partner_type_views.xml',
        'views/vendor_blacklist_views.xml',
        'views/sale_order_views.xml',
        'views/stock_picking_views.xml',  #
        'views/stock_move_views.xml',  #
        'views/stock_move_line_views.xml',
        'views/stock_picking_type_views.xml',
        'views/res_users_views.xml',
        'views/res_assignee_views.xml',
        'views/res_assignee_po_views.xml',
        'views/res_assignee_pr_views.xml',
        'views/res_assignee_invoice_views.xml',
        'views/res_assignee_payment_views.xml',
        'views/res_assignee_bill_views.xml',
        'views/purchase_request_type_views.xml',
        'views/purchase_request_type_second_views.xml',
        'views/res_buyer_views.xml',
        'views/res_currency_views.xml',
        'views/account_analytic_account_views.xml',
        'views/account_asset_views.xml',
        # 'views/purchase_bill_union_views.xml',
        'views/product_template_views.xml',
        'views/purchase_request_views.xml',
        'views/purchase_request_line_views.xml',
        'views/web_template.xml',
        'views/cf_activity_view.xml',
        'views/cf_category_view.xml',
        'views/miscellaneous_payment.xml',
        'views/miscellaneous_receipt.xml',
        'views/applied_bill_views.xml',
        'views/applied_invoice_views.xml',
        'views/bank_cash_transfer_view.xml',
        'views/res_config_settings_views.xml',
        'views/sale_subscription_views.xml',
        'views/report_financial.xml',
        'views/report_styles.xml',
        'views/decimal_precision_views.xml',
        'views/account_bank_statement_views.xml',
        'views/account_bank_statement_line_views.xml',
        'views/account_bank_statement_generate.xml',
        'views/payment_purchase_order_views.xml',
        # 'views/project_task_views.xml',
        'views/res_project_main_views.xml',
        'views/crossovered_budget_views.xml',
        'views/account_budget_category_views.xml',
        'views/account_account_views.xml',
        'report/report_views.xml',
        'report/report_batch_payment_templates.xml',
        'report/report_auto_invoice_cetak.xml',
        'report/report_credit_note.xml',
        # 'report/report_invoice_ap.xml',
        'report/report_ar_receipt.xml',
        'report/report_ar_receipt_misc.xml',
        'report/report_invoice_ar_mnctv_templates.xml',
        'report/report_form_inventory_templates.xml',
        'report/report_invoice_mnc_templates.xml',
        # 'report/report_invoice_mnc_land_templates.xml',
        'report/report_invoice_ar_manual.xml',
        'report/report_invoice_ar_memo.xml',
        # 'report/report_credit_memo_mncp_templates.xml',
        # 'report/report_debit_memo_mncp_templates.xml',
        'report/report_invoice_logprove_digital.xml',
        'report/report_invoice_manual_airtime.xml',
        'report/report_invoice_manual_non_airtime.xml',
        'report/report_journal_voucher.xml',
        'report/report_purchase_order.xml',
        'report/report_purchase_order_vendor_site.xml',
        # 'report/report_purchase_order_mncp.xml',
        # 'report/report_purchase_order_mnc_land.xml',
        'report/report_purchase_order_service.xml',
        'report/report_purchase_request.xml',
        'report/report_purchase_request_service.xml',
        'report/report_general_terms_purchase_order.xml',
        # 'report/report_payment_voucher_mnc_land.xml',
        # 'report/report_payment_voucher_mncp.xml',
        # 'report/report_payment_slip_mncp_templates.xml',
        'report/report_rr.xml',
        'report/report_rr_service.xml',
        'report/report_bukti_terima_barang.xml',
        'report/report_inventory_issue_slip.xml',
        'report/report_request_for_payment.xml',
        # 'report/report_request_for_payment_mncp.xml',
        'report/report_invoice_receipt_templates.xml',
        'report/ins_base_mnc_report_views.xml',
        'report/purchase_payment_report_views.xml',
        'report/cash_flow_report.xml',
        'report/report_payment_invoice_templates.xml',
        'report/report_payment_purchase_order.xml',
        'report/report_purchase_requisition.xml',
        # 'report/report_invoice_ap_voucher_mnc_land.xml',
        # 'report/report_form_check_mncp.xml',
        # 'report/report_payment_pv_rcti.xml',
        # 'report/report_payment_po_rcti.xml',
        'wizards/gr_matching_wizard.xml',
        'wizards/gr_expense_receive.xml',
        'wizards/gr_consumable_receive.xml',
        'wizards/payment_invoice_views.xml',
        'wizards/invoice_recap_report_views.xml',
        'wizards/payment_recap_report_views.xml',
        'wizards/invoice_receipt_views.xml',
        'wizards/purchase_request_line_make_purchase_order_views.xml',
        'wizards/asset_detail_report_views.xml',
        'wizards/standard_ap_detail_report_views.xml',
        'wizards/all_ap_invoices_report_views.xml',
        'wizards/account_bank_statment_generate.xml',
        'wizards/account_payment_register_views.xml',
        'wizards/stock_return_picking_views.xml',
        'wizards/action_remitted_views.xml',
        'wizards/action_remitted_receipt_views.xml',
        'wizards/cover_note.xml',
        'wizards/settlement_ca_report.xml',
        'wizards/trial_balance_views.xml',
        'views/temporary_edit_sequence_views.xml',
        'views/res_sites_views.xml',
        'views/res_partner_remit_views.xml',
        'views/report_config/report_config_views.xml',
        'views/receipt_period.xml',
        'views/receipt_period_line.xml',
        'views/payment_period.xml',
        'views/payment_period_line.xml',
        'views/res_payment_document_views.xml',
        'views/res_check_views.xml',
        'views/res_giro_views.xml',
        'views/applied_prepayment_to_bill.xml',
        'views/res_company_logo_views.xml',
    ],
    'qweb': [
        'static/src/xml/purchase_dashboard.xml',
        'static/src/xml/account_payment.xml',
        'static/src/xml/base.xml',
    ]
}
