{
    "name": "Base Module for 3TV and MNCP",
    "version": "14.0.0.1",
    "description": """
        Base Module for 3TV and MNCP
    """,
    'license': 'LGPL-3',
    "author": "Invosa Systems",
    "website": 'http://invosa.com/',
    'category': "Hidden",
    'summary': "Base Module for 3TV and MNCP",
    "depends": [
        "purchase_request",
        # "account",
        'account_document_reversal',
        'ins_accounting',
        'ins_base_mnc',
        'purchase',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/ir_cron.xml',
        'views/mnc_operating_unit_views.xml',
        'views/account_move_views.xml',
        'views/res_partner_views.xml',
        'views/stock_picking_views.xml',
        'views/purchase_request_views.xml',
        'views/account_payment_views.xml',
        'views/uom_uom_views.xml',
        'report/report_views.xml',
        'report/report_check_bca_templates.xml',
        'report/report_check_bri_templates.xml',
        'report/report_check_bjb_templates.xml',
        'report/report_check_capital_templates.xml',
        'report/report_check_mandiri_templates.xml',
        'report/report_check_mncbank_templates.xml',
        # 'report/report_check_muamalat_templates.xml',
        'report/report_check_permata_templates.xml',
        'report/report_check_sinarmas_templates.xml',
        'report/report_giro_bca_templates.xml',
        'report/report_giro_bjb_templates.xml',
        'report/report_giro_bri_templates.xml',
        'report/report_giro_btn_templates.xml',
        'report/report_giro_capital_templates.xml',
        'report/report_giro_cimb_templates.xml',
        'report/report_giro_mandiri_templates.xml',
        'report/report_giro_mnc_templates.xml',
        'report/report_giro_permata_templates.xml',
        'report/report_giro_sinarmas_templates.xml',
        'report/report_payment_slip_bca_templates.xml',
        'report/report_payment_slip_bri_templates.xml',
        'report/report_payment_slip_bjb_templates.xml',
        'report/report_payment_slip_mncbank_templates.xml',
        'report/report_payment_slip_kliring_mandiri_templates.xml',
        'report/report_payment_slip_multi_mandiri_templates.xml',
        'report/report_purchase_request_mncp.xml',
        'report/report_purchase_request_3tv_templates.xml',
        'report/report_credit_memo_mncp_templates.xml',
        'report/report_debit_memo_mncp_templates.xml',
        'report/report_purchase_order_mncp.xml',
        'report/report_payment_order_3tv.xml',
        'report/report_payment_voucher_mncp.xml',
        'report/report_payment_request_gtv_templates.xml',
        'report/report_payment_slip_mncp_templates.xml',
        'report/report_request_for_payment_mncp.xml',
        'report/report_form_check_mncp.xml',
        'report/report_payment_pv_rcti.xml',
        'report/report_payment_po_rcti.xml',
        'report/report_invoice_ar_mnctv_templates.xml',
        'report/report_request_for_payment_mncp.xml',
        'report/report_cash_advance_pih_templates.xml',
        'report/report_payment_request_pih_templates.xml',
        'report/report_purchase_request_pih_templates.xml',
        'report/report_cash_advance_non_pih_templates.xml',
        'report/report_payment_request_non_pih_templates.xml',
        'report/report_purchase_request_non_pih_templates.xml',
        'report/report_request_spd_pih_templates.xml',
        'report/report_request_spd_non_pih_templates.xml',
        'report/report_petty_cash_request_templates.xml',
        'wizards/invoice_receipt_3tv_views.xml',
        'report/report_invoice_receipt_3tv_templates.xml',
    ],
    'qweb': [
        # 'static/src/xml/pos_receipt.xml',
    ],
}
